### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kFxDaKing** [Blumlaut/RottenV#1]
https://imgur.com/a/qofw4Ix

**Comment by Blumlaut** [comment]
Hi! Thank you for your Bug Report, however, please use our [Bug Report Template](https://github.com/Bluethefurry/RottenV/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) when reporting Issues! You can edit your existing Issue and reopen it once you have added all necesarry infos!
