### ISSUE TITLE
Bug Report RottenV Item Spawner

### ISSUE THREAD

**Issue by Hugoo1275** [Blumlaut/RottenV#14]
**Describe the bug**
When a player joins the server they gets stuck in "Awaiting Scripts.." and an error shows up in console.

**To Reproduce**

**Expected behavior**
I tought it would run without any error or any problems

**Changes done to the Gamemode**
I haven't changed anything i followed this wiki [](https://github.com/Blumlaut/RottenV/wikil)

**Screenshots/Videos**
No images needed

**Logs**
`Error resuming coroutine: server/spawners/itemspawner_server.lua:121: attempt to call a nil value (global 'DoesEntityExist')
stack traceback:
        server/spawners/itemspawner_server.lua:121: in function <server/spawners/itemspawner_server.lua:107>`

**Additional context**
No further context

**Comment by iSentrie** [comment]
Clearly you did something wrong, it works out of the box.

**Comment by Blumlaut** [comment]
You need to enable Onesync Legacy on your Server to use RottenV.

**Comment by Hugoo1275** [comment]
where can i get Onesync Legacy?

**Comment by Blumlaut** [comment]
add `+set onesync on` or `+set onesync legacy` to your server parameters

**Comment by Hugoo1275** [comment]
i getting the same error: `Error resuming coroutine: server/spawners/itemspawner_server.lua:121: attempt to call a nil value (global 'DoesEntityExist')
stack traceback:
        server/spawners/itemspawner_server.lua:121: in function <server/spawners/itemspawner_server.lua:107>`

**Comment by Blumlaut** [comment]
Which Server Artifact are you on? most likely your artifact is extremely old
