### ISSUE TITLE
No parachute after death

### ISSUE THREAD

**Issue by efexaa** [Blumlaut/RottenV#18]
**Describe the bug**
After dying end up straight on the ground somewhere on the map instead of in the sky with parachute... 
after dying multiple times you end up in the sky with parachute, bet next time again straight on the ground

**To Reproduce**
 To be killed

**Expected behavior**
After dying i would expect to be in the sky with parachute

**Changes done to the Gamemode**
N/a

**Screenshots/Videos**

**Logs**

**Additional context**

**Comment by Blumlaut** [comment]
make sure that no other resource that adds spawnpoints starts, e.g. no fivem-map-* resources.

**Comment by efexaa** [comment]
He deleted no fivem- map and then map isnt loaded.. all scrips goes awaiting script and crashes server

**Comment by Blumlaut** [comment]
you need to make sure `fivem` is still being started.

**Comment by efexaa** [comment]
Dont want to be a dick but he asked what actually you mean?

**Comment by Blumlaut** [comment]
fivem, or `basic-gamemode` needs to be started.
