### ISSUE TITLE
Air Drop not functioning

### ISSUE THREAD

**Issue by efexaa** [Blumlaut/RottenV#19]
**Describe the bug**
Air Drop keeps saying you need to be higher..

**To Reproduce**

You find Air Drop and use through M function. 

**Expected behavior**
Before it used to work on any ground anywhere on the map... now it keeps saying you need to be higher to work.. and airdrop dissapears

**Changes done to the Gamemode**
no

**Screenshots/Videos**
N/A

**Logs**
N/A

**Additional context**

**Comment by ghost** [comment]
@efexaa Check new version

**Comment by Blumlaut** [comment]
closing since stale.
