### ISSUE TITLE
There is no guide in the wiki

### ISSUE THREAD

**Issue by Staydown03** [Blumlaut/RottenV#22]
**Is your feature request related to a problem? Please describe.**
The issue is that there is no guide or steps in the wiki. I don't know how to fully install this mod

**Describe the solution you'd like**
Is there any way you could provide the steps

**Describe alternatives you've considered**
Maybe you could make a video but

**Additional context**

**Comment by Blumlaut** [comment]
Installation is trivial, you install it like any other resource ever made for FiveM, there are no extra steps, hence there is no installation guide.
