### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by TheSyntaxJunkie** [Blumlaut/RottenV#33]
....

**Comment by TheSyntaxJunkie** [comment]
....

**Comment by Blumlaut** [comment]
rottenv is standalone and should not be used alongside other frameworks, the documentation says what it needs to, this is not an idiot-proof gamemode but a dump of a server that was closed, unless you are planning to pay me you should be able to figure this out yourself, basic fivem and database skills are expected.

**Comment by TheSyntaxJunkie** [comment]
The fact you think your guide explains any of that is foolish at best and shows your level as a developer, knowing how to code just does not make you "automatically" able to understand everything. There is documentation for a reason. I am guessing you know what that reason is? Also, standalone could be used in many contexts, you know how you can have standalone scripts in qbcore or esx?

**Comment by Blumlaut** [comment]
it's frankly stunning how little of a shit I give about wannabe experts like you, if you have a problem with the docs then either write some yourself or build your own gamemode, your input is not welcome.

**Comment by TheSyntaxJunkie** [comment]
I really don't care how a half-assed fake developer feels tbh, its pathetic you call your self that. now have a seat.

**Comment by Blumlaut** [comment]
I literally wrote this gamemode.
