### ISSUE TITLE
Taking Damage Unknown Reason

### ISSUE THREAD

**Issue by ScrachStack** [Blumlaut/RottenV#37]
**Describe the bug**

**To Reproduce**
1. Go on server spawn in and then shortly die

**Expected behavior**
Trying to Play
**Changes done to the Game mode**
None
**Screenshots/Videos**
![image](https://github.com/Blumlaut/RottenV/assets/122732007/57b918f0-482e-4f50-9abf-d3a8b5d1c633)

**Additional context**
My player is taking damage as soon as he spawns in until he dies and this is happened 30 times now.

**Comment by BostonRiot95** [comment]
@duckylarps  Maybe the rate multiplier for hunger etc? Check your config

**Comment by ghost** [comment]
Fixed in #38
