### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by stilmon** [Blumlaut/RottenV#39]
RottenV/
├── client/
│   ├── inventory/
│   │   └── inventory_c.lua (placeholder or actual script)
├── server/
│   ├── gameplay/
│   │   └── drops.lua (placeholder or actual script)
├── fxmanifest.lua

drops.lua 
and
inventory_c.lua are missing i am getting this error when starting it

**Comment by stilmon** [comment]
also   c-resources-core] Could not find dependency pogressBar for resource RottenV.

**Comment by stilmon** [comment]
will gladly pay to have this resolved on my own dedicated server. if you wanna reach out to me direct

**Comment by Blumlaut** [comment]
> also c-resources-core] Could not find dependency pogressBar for resource RottenV.

have you read the wiki?
https://github.com/Blumlaut/RottenV/wiki/INSTALL

**Comment by stilmon** [comment]
Yes, followed it to the T also,

citizen-server-impl] Couldn't start resource RottenV.


always seem to get this, I commented the missing foles from manifest cause I seen they where deleted

**Comment by Blumlaut** [comment]
Couldn't start resource is always associated with another error, you are likely missing dependencies, refer to the wiki for what you need.

**Comment by stilmon** [comment]
Because I'm a systems engineer and do mainly datacenters and not so much video games, do you have a charge or way to contact you and get you into this server and setup? ill gladly pay. I'm sure its something I'm missing simple.

**Comment by Blumlaut** [comment]
> do you have a charge

No

> or way to contact you

You are in contact with me right now..?

> and get you into this server and setup?

No

> ill gladly pay.

I mean, if you hate money so much, feel free to give some to me? but its not going to make me help you any more than i am currently trying to.

provide a proper log with the full error, make sure your dependencies are installed (resource names MUST be correct, e.g no -master at the end and such).

**Comment by stilmon** [comment]
[    c-server-monitor] ←[0m  _______  ______
[    c-server-monitor] ←[0m |  ___\ \/ / ___|  ___ _ ____   _____ _ __
[    c-server-monitor] ←[0m | |_   \  /\___ \ / _ \ '__\ \ / / _ \ '__|
[    c-server-monitor] ←[0m |  _|  /  \ ___) |  __/ |   \ V /  __/ |
[    c-server-monitor] ←[0m |_|   /_/\_\____/ \___|_|    \_/ \___|_|
[    c-server-monitor] ←[0m-------------------------------- monitor ---
[    c-server-monitor] ←[0m
[    c-scripting-core] ←[0mCreating script environments for monitor
[14:35:37][tx:v6.0.2] Profile 'default' starting...
[14:35:37][tx:WebServer] Listening on 0.0.0.0.
[14:35:38][tx]
[14:35:38][tx]    ?????????????????????????????????????
[14:35:38][tx]    ?                                   ?
[14:35:38][tx]    ?     All ready! Please access:     ?
[14:35:38][tx]    ?      http://localhost:40120/      ?
[14:35:38][tx]    ?    http://97.105.175.50:40120/    ?
[14:35:38][tx]    ?                                   ?
[14:35:38][tx]    ?????????????????????????????????????
[14:35:38][tx]
[14:35:38][tx] To be able to access txAdmin from the internet open port 40120
[14:35:38][tx] on your OS Firewall as well as in the hosting company.
[14:35:38][tx:FXRunner] >> [5856] FXServer Started!

================================================================
======== FXServer Starting - 7/9/2024, 2:35:38 PM
================================================================
[14:35:38][tx:UpdateChecker] This version of txAdmin is outdated.
[14:35:38][tx:UpdateChecker] Please update as soon as possible.
[14:35:38][tx:UpdateChecker] For more information: https://discord.gg/uAmsGa2
[           resources] Scanning resources.
[           resources] Found 100 resources.
[          svadhesive] Authenticating server license key...
[          svadhesive] Server license key authentication succeeded. Welcome!
[    c-scripting-core] Creating script environments for sessionmanager
[           resources] Started resource sessionmanager
[    c-scripting-core] Creating script environments for monitor
[      script:monitor] [txAdmin] Resource v6.0.2 threads and commands set up. Al
l Ready.
[           resources] Started resource monitor
[    c-scripting-core] Creating script environments for mapmanager
[           resources] Started resource mapmanager
[    c-scripting-core] Creating script environments for yarn
[           resources] Started resource yarn
[    c-scripting-core] Creating script environments for webpack
[           resources] Started resource webpack
[    c-scripting-core] Creating script environments for chat
[           resources] Started resource chat
[           resources] Started resource spawnmanager
[   script:mapmanager] Started gametype Freeroam
[           resources] Started resource basic-gamemode
[    c-scripting-core] Creating script environments for hardcap
[           resources] Started resource hardcap
[    c-scripting-core] Creating script environments for baseevents
[           resources] Started resource baseevents
[    c-scripting-core] Creating script environments for oxmysql
[           resources] Started resource oxmysql
[    c-scripting-core] Creating script environments for qb-core
[           resources] Started resource qb-core
[           resources] Started resource menuv
[    c-scripting-core] Creating script environments for qb-adminmenu
[           resources] Started resource qb-adminmenu
[    c-scripting-core] Creating script environments for qb-ambulancejob
[           resources] Started resource qb-ambulancejob
[           resources] Started resource qb-interior
[    c-scripting-core] Creating script environments for qb-clothing
[           resources] Started resource qb-clothing
[    c-scripting-core] Creating script environments for qb-weathersync
[           resources] Started resource qb-weathersync
[    c-scripting-core] Creating script environments for qb-apartments
[           resources] Started resource qb-apartments
[    c-scripting-core] Creating script environments for qb-banking
[           resources] Started resource qb-banking
[    c-scripting-core] Creating script environments for PolyZone
[           resources] Started resource PolyZone
[    c-scripting-core] Creating script environments for qb-bankrobbery
[           resources] Started resource qb-bankrobbery
[    c-scripting-core] Creating script environments for qb-busjob
[           resources] Started resource qb-busjob
[    c-scripting-core] Creating script environments for qb-cityhall
[           resources] Started resource qb-cityhall
[    c-scripting-core] Creating script environments for qb-crafting
[           resources] Started resource qb-crafting
[           resources] Started resource qb-minigames
[    c-scripting-core] Creating script environments for qb-crypto
[           resources] Started resource qb-crypto
[    c-scripting-core] Creating script environments for qb-diving
[           resources] Started resource qb-diving
[    c-scripting-core] Creating script environments for qb-doorlock
[           resources] Started resource qb-doorlock
[    c-scripting-core] Creating script environments for qb-drugs
[           resources] Started resource qb-drugs
[    c-scripting-core] Creating script environments for qb-garages
[           resources] Started resource qb-garages
[    c-scripting-core] Creating script environments for qb-garbagejob
[           resources] Started resource qb-garbagejob
[    c-scripting-core] Creating script environments for qb-hotdogjob
[           resources] Started resource qb-hotdogjob
[    c-scripting-core] Creating script environments for qb-houserobbery
[           resources] Started resource qb-houserobbery
[    c-scripting-core] Creating script environments for qb-houses
[           resources] Started resource qb-houses
[    c-scripting-core] Creating script environments for qb-hud
[           resources] Started resource qb-hud
[           resources] Started resource qb-input
[    c-scripting-core] Creating script environments for qb-weapons
[           resources] Started resource qb-weapons
[    c-scripting-core] Creating script environments for qb-inventory
[           resources] Started resource qb-inventory
[    c-scripting-core] Creating script environments for qb-jewelery
[           resources] Started resource qb-jewelery
[    c-scripting-core] Creating script environments for qb-lapraces
[           resources] Started resource qb-lapraces
[           resources] Started resource qb-loading
[    c-scripting-core] Creating script environments for qb-management
[           resources] Started resource qb-management
[    c-scripting-core] Creating script environments for qb-mechanicjob
[           resources] Started resource qb-mechanicjob
[           resources] Started resource qb-menu
[    c-scripting-core] Creating script environments for qb-spawn
[           resources] Started resource qb-spawn
[    c-scripting-core] Creating script environments for qb-multicharacter
[           resources] Started resource qb-multicharacter
[    c-scripting-core] Creating script environments for qb-newsjob
[           resources] Started resource qb-newsjob
[    c-scripting-core] Creating script environments for qb-pawnshop
[           resources] Started resource qb-pawnshop
[    c-scripting-core] Creating script environments for qb-phone
[           resources] Started resource qb-phone
[    c-scripting-core] Creating script environments for qb-policejob
[           resources] Started resource qb-policejob
[    c-scripting-core] Creating script environments for qb-prison
[           resources] Started resource qb-prison
[    c-scripting-core] Creating script environments for qb-radialmenu
[           resources] Started resource qb-radialmenu
[    c-scripting-core] Creating script environments for qb-recyclejob
[           resources] Started resource qb-recyclejob
[    c-scripting-core] Creating script environments for qb-scoreboard
[           resources] Started resource qb-scoreboard
[    c-scripting-core] Creating script environments for qb-scrapyard
[           resources] Started resource qb-scrapyard
[    c-scripting-core] Creating script environments for qb-shops
[           resources] Started resource qb-shops
[    c-scripting-core] Creating script environments for qb-smallresources
[           resources] Started resource qb-smallresources
[    c-scripting-core] Creating script environments for qb-storerobbery
[           resources] Started resource qb-storerobbery
[    c-scripting-core] Creating script environments for qb-streetraces
[           resources] Started resource qb-streetraces
[           resources] Started resource qb-target
[    c-scripting-core] Creating script environments for qb-taxijob
[           resources] Started resource qb-taxijob
[    c-scripting-core] Creating script environments for qb-towjob
[           resources] Started resource qb-towjob
[    c-scripting-core] Creating script environments for qb-truckrobbery
[           resources] Started resource qb-truckrobbery
[    c-scripting-core] Creating script environments for qb-vehiclekeys
[           resources] Started resource qb-vehiclekeys
[    c-scripting-core] Creating script environments for qb-vehiclesales
[           resources] Started resource qb-vehiclesales
[    c-scripting-core] Creating script environments for qb-vehicleshop
[           resources] Started resource qb-vehicleshop
[    c-scripting-core] Creating script environments for qb-vineyard
[           resources] Started resource qb-vineyard
[    c-scripting-core] Creating script environments for qb-weed
[           resources] Started resource qb-weed
[    c-scripting-core] Creating script environments for LegacyFuel
[           resources] Started resource LegacyFuel
[           resources] Started resource bob74_ipl
[    c-scripting-core] Creating script environments for connectqueue
[ script:connectqueue] QUEUE:  [connectqueue] Disabling hardcap
[           resources] Stopping resource hardcap
[           resources] Started resource connectqueue
[    c-scripting-core] Creating script environments for interact-sound
[           resources] Started resource interact-sound
[           resources] Started resource progressbar
[           resources] Started resource safecracker
[    c-scripting-core] Creating script environments for screenshot-basic
[           resources] Started resource screenshot-basic
[    c-scripting-core] Creating script environments for pma-voice
[           resources] Started resource pma-voice
[    c-scripting-core] Creating script environments for qb-radio
[           resources] Started resource qb-radio
[           resources] Started resource dealer_map
[           resources] Started resource hospital_map
[           resources] Started resource prison_canteen
[resources:prison_mai] Asset prison_main/desertos_prison.ytd uses 30.5 MiB of ph
ysical memory.
[           resources] Started resource prison_main (1 warning)
[           resources] Started resource prison_meeting
[           resources] Started resource pogressBar
[    c-scripting-core] Creating script environments for RottenV
[   script:mapmanager] Started map RottenV
[resources:RottenV:st] Asset RottenV/rottenv.ytd uses 28.5 MiB of physical memor
y.
[           resources] Started resource RottenV (1 warning)
[      script:RottenV]
[      script:RottenV] Updating all Safes...
[      script:oxmysql] [10.4.32-MariaDB] Database server connection established!

[ script:qb-inventory] 1 inventories successfully loaded
[ citizen-server-impl]         fff
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee
[ citizen-server-impl]



resources standalone hold

oxmysql

**Comment by Blumlaut** [comment]
first of all, it looks like you are using QBCore, do note that RottenV is explicitly not designed to run alongside any other gamemodes or frameworks, that may/likely will cause problems, if you want to use RottenV you should use the official cfx-server-data install and nothing else.

Also, RottenV is starting fine according to those logs.

**Comment by stilmon** [comment]
Roger that, resettin
first of all, it looks like you are using QBCore, do note that RottenV is explicitly not designed to run alongside any other gamemodes or frameworks, that may/likely will cause problems, if you want to use RottenV you should use the official cfx-server-data install and nothing else.

Also, RottenV is starting fine according to those logs.

—

**Comment by stilmon** [comment]
well getting closer   server reinstalled with what you recommended  (thanks for patience)
however i get no errors in logs (see below)

======== FXServer Starting - 7/9/2024, 3:36:57 PM               
================================================================

[           resources] Scanning resources.
[           resources] Found 28 resources.
[          svadhesive] Authenticating server license key...
[          svadhesive] Server license key authentication succeeded. Welcome!
[    c-scripting-core] Creating script environments for sessionmanager
[           resources] Started resource sessionmanager
[    c-scripting-core] Creating script environments for monitor
[      script:monitor] [txAdmin] Resource v6.0.2 threads and commands set up. All Ready.
[           resources] Started resource monitor
[    c-scripting-core] Creating script environments for mapmanager
[           resources] Started resource mapmanager
[    c-scripting-core] Creating script environments for yarn
[           resources] Started resource yarn
[    c-scripting-core] Creating script environments for webpack
[           resources] Started resource webpack
[    c-scripting-core] Creating script environments for chat
[           resources] Started resource chat
[           resources] Started resource spawnmanager
[   script:mapmanager] Started gametype Freeroam
[           resources] Started resource basic-gamemode
[    c-scripting-core] Creating script environments for hardcap
[           resources] Started resource hardcap
[           resources] Started resource pogressBar
[    c-scripting-core] Creating script environments for oxmysql
[           resources] Started resource oxmysql
[    c-scripting-core] Creating script environments for RottenV
[   script:mapmanager] Started map RottenV
[resources:RottenV:st] Asset RottenV/rottenv.ytd uses 28.5 MiB of physical memory.
[           resources] Started resource RottenV (1 warning)
[      script:RottenV] 
[      script:RottenV] Updating all Safes...
[      script:oxmysql] [10.4.32-MariaDB] Database server connection established!
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://umbrella-corp-glqrb9.users.cfx.re/
[      script:RottenV] 
[      script:RottenV] Updated Safes. 0



however when the mod rottenV is enabled it has me switch versions and client log shows

 [b3095_GTAProce]             MainThrd/ Creating script environments for RottenV
[    127781] [b3095_GTAProce]             MainThrd/ SET_MANUAL_SHUTDOWN_LOADING_SCREEN_NUI is not supported at this time. Use `loadscreen_manual_shutdown 'yes'` in your fxmanifest.lua instead.
[    127796] [b3095_GTAProce]             MainThrd/ Loading mounted data files (total: 1)
[    127796] [b3095_GTAProce]             MainThrd/ loading DLC_ITYP_REQUEST resources:/RottenV/stream/def_props.ytyp.
[    127796] [b3095_GTAProce]             MainThrd/ done loading resources:/RottenV/stream/def_props.ytyp in data file mounter 0x7ff9a65e2f38.
[    127796] [b3095_GTAProce]             MainThrd/ OnConnectionProgress: Mounted RottenV (1 of 1)
[    127828] [b3095_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @RottenV/client/gameplay/nopeds.lua:55: attempt to perform arithmetic on a nil value (global 'x')^7
[    127828] [b3095_GTAProce]             MainThrd/ ^3> fn^7 (^5@RottenV/client/gameplay/nopeds.lua^7:55)
[    128875] [b3095_GTAProce]             MainThrd/ ^3Warning: SET_PED_COMBAT_ATTRIBUTES: invalid attribute index was passed (1424), should be from 0 to 91^7
[    129218] [b3095_GTAProce]             MainThrd/ ^3Warning: SET_PED_COMBAT_ATTRIBUTES: invalid attribute index was passed (1424), should be from 0 to 91^7
[    129890] [b3095_GTAProce]             MainThrd/ Error: [md]# Disconnected by server
[    129890] [b3095_GTAProce]             MainThrd/ Identifier Authentication Failed. Please make sure Steam is running and you are opted-out of Steam Beta.
[    130015] [b3095_GTAProce]             MainThrd/ Killing network: [md]# Disconnected by server
[    130015] [b3095_GTAProce]             MainThrd/ Identifier Authentication Failed. Please make sure Steam is running and you are opted-out of Steam Beta.
[    130093] [b3095_GTAProce]             MainThrd/ Killing network, stage 2...
[    130375] [b3095_GTAProce]             MainThrd/ Shutdown: waiting for streaming to finish
[    130375] [b3095_GTAProce]             MainThrd/ Shutdown: canceling requests
[    130375] [b3095_GTAProce]             MainThrd/ Shutdown: updating GTA streamer state
[    130375] [b3095_GTAProce]             MainThrd/ Shutdown: unloading texture LODs
[    130375] [b3095_GTAProce]             MainThrd/ Shutdown: streamer tasks done
[    130375] [b3095_GTAProce]             MainThrd/ Running shutdown session function: 0x1409508a0
[    130875] [    SteamChild]             MainThrd/ CitizenFX Steam child starting - command line: "C:\Users\Scott Cadieux\AppData\Local\FiveM\FiveM.app\data\cache\subprocess\FiveM_SteamChild.exe" -steamparent:13008
[    130875] [    SteamChild]             MainThrd/ Initializing Steam parent.
[    130953] [    SteamChild]             MainThrd/ Initializing Steam parent: Steam's running.
[    131093] [    SteamChild]             MainThrd/ Initializing Steam parent: Initializing presence.
[    131109] [    SteamChild]             MainThrd/ Initializing Steam parent: Attempting to run processes.
[    131843] [    SteamChild]             MainThrd/ CitizenFX Steam child starting - command line: "C:\Users\Scott Cadieux\AppData\Local\FiveM\FiveM.app\data\cache\subprocess\FiveM_SteamChild.exe" -steamchild:22124
[    131843] [    SteamChild]             MainThrd/ game parent PID: 22124
[    131843] [    SteamChild]             MainThrd/ waiting for process to exit...

i am not in the steam beta program and this only happens when mod is activated.  all other errors seem gone 
![Screenshot 2024-07-09 154025](https://github.com/Blumlaut/RottenV/assets/26150110/e34009ea-57a7-4c67-9080-ae4183cf490a)

**Comment by stilmon** [comment]
maybe needs to run a specific version of game? not quite sure.  super  confusing

**Comment by Blumlaut** [comment]
you need to configure your steam web api key. https://docs.fivem.net/docs/server-manual/server-commands/#steam_webapikey-key

**Comment by stilmon** [comment]
let me try that part

**Comment by stilmon** [comment]
I got this working, thanks for your help.

1. Removed the missing files from the manifest (that are no longer needed)
2. removed qbcore and installed base cfx server
3. added steam key
