### ISSUE TITLE
No loot from Red Zombies

### ISSUE THREAD

**Issue by efexaa** [Blumlaut/RottenV#9]
**Describe the bug**
After killing Red Zombie no loot appears

**To Reproduce**
N/a

**Expected behavior**
Shit loads of ammo and guns from red zombies

**Changes done to the Gamemode**
N/A

**Screenshots/Videos**
N/A

**Logs**
N/A

**Additional context**
N/A

**Comment by Blumlaut** [comment]
this bug is referenced in https://github.com/Bluethefurry/RottenV/issues/7
